apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: 3.16.108.69:8081/artifactory/kierandocker/helloweb:latest
        ports:
        - name: http-port
          containerPort: 80